name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          pip3 install -r requirements.txt

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Deploy
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        run: |
          ssh ec2-user@${{ secrets.EC2_INSTANCE_IP }} "cd ~/bot && git pull origin main && python3 bot.py"
